server:
  port: ${DSQ_APP_PORT:7979}
spring:
  codec:
    max-in-memory-size: 1000KB
  application:
    name: ${DSQ_APP_NAME:DSQService}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: postgres
    password: Shoxruh0912
    url: jdbc:postgresql://localhost:5432/xarid_mf_uz
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    groups-order: asc
    operations-sorter: alpha
    try-it-out-enabled: true
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /api/doc
queue:
  name:
    dsq: cportal_tax_in
api:
  info:
    title: Davlat Xaridlari Markaziy Axborot Portali
    description: Davlat Xaridlari Markaziy Axborot Portali proyektidagi API lar
    version: 1.2
    contact-name: Viktor Dimkov
    contact-email: theshd.0912@gmail.com
    contact-url: https://t.me/Cor_habe
    license-name: https://xarid.mf.uz
    license-url: https://xarid.mf.uz
dsq:
  api:
    user: "nimadr"
    password: "nimadr"
    url:
      protocol: "https://"
      domain: "mspd-api.soliq.uz"
      path:
        login-api: "/minfin2/api/authenticate/login"
        juridic-info-api: "/nimadr"
        individual-info-api: "/nimadr"
        financial-statements-form-one-api: "/nimadr"
        financial-statements-form-two-api: "/nimadr"
        doubtful-taxpayer-api: "/nimadr"
        purchase-info-api: "/nimadr"
        tax-gap-info-api: "nimadr"

tax:
  excel:
    url: https://soliq.uz/activities/analysis/download/excel

request:
  id:
    file:
      path: /home/shoxruh/requestId.dat
rabbit:
  dev:
    username: username
    password: password
    port: 5672
    host: dev-rabbit.mf.uz
  prod:
    username: username
    password: password
    port: 5672
    host: prod-rabbit.mf.uz
  routing-key:
    xt-xarid: xt.request
    uz-ex: uzex.request
    co-operation: co.request
    shaffof: shaffof.request
  exchanges:
    topic-exchange: common
    fanout-exchange: etp_broadcast

